# Generated by Django 6.0.1 on 2026-02-06 16:49
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        # -----------------------------
        # FACE DATA
        # -----------------------------
        migrations.RemoveField(
            model_name='facedata',
            name='created_at',
        ),
        migrations.AddField(
            model_name='facedata',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),

        # -----------------------------
        # ATTENDANCE
        # -----------------------------
        migrations.AddField(
            model_name='attendance',
            name='marked_at',
            field=models.DateTimeField(auto_now=True),
        ),

        # -----------------------------
        # CLASSROOM
        # -----------------------------
        migrations.AddField(
            model_name='classroom',
            name='created_at',
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='classroom',
            name='year',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),

        # -----------------------------
        # FACULTY
        # -----------------------------
        migrations.AddField(
            model_name='faculty',
            name='created_at',
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='faculty',
            name='is_active',
            field=models.BooleanField(default=True),
        ),

        # -----------------------------
        # STUDENT
        # -----------------------------
        migrations.AddField(
            model_name='student',
            name='created_at',
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='is_active',
            field=models.BooleanField(default=True),
        ),

        # -----------------------------
        # SUBJECT
        # -----------------------------
        migrations.AddField(
            model_name='subject',
            name='created_at',
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),

        # -----------------------------
        # ALTER FIELDS
        # -----------------------------
        migrations.AlterField(
            model_name='classroom',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='classroom',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='students',
                to='backend.classroom'
            ),
        ),
        migrations.AlterField(
            model_name='student',
            name='parent_contact',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='subject',
            name='classroom',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='subjects',
                to='backend.classroom'
            ),
        ),
        migrations.AlterField(
            model_name='subject',
            name='faculty',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='subjects',
                to='backend.faculty'
            ),
        ),
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together={('name', 'classroom')},
        ),

        # -----------------------------
        # ATTENDANCE SESSION
        # -----------------------------
        migrations.CreateModel(
            name='AttendanceSession',
            fields=[
                ('id', models.BigAutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False,
                    verbose_name='ID'
                )),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('classroom', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    to='backend.classroom'
                )),
                ('faculty', models.ForeignKey(
                    null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    to='backend.faculty'
                )),
                ('subject', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    to='backend.subject'
                )),
            ],
            options={
                'unique_together': {('classroom', 'subject', 'date')},
            },
        ),

        # -----------------------------
        # ATTENDANCE RESTRUCTURE
        # -----------------------------
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='attendance',
            name='attendance_session',
            field=models.ForeignKey(
                null=True,   # IMPORTANT for existing rows
                on_delete=django.db.models.deletion.CASCADE,
                related_name='records',
                to='backend.attendancesession'
            ),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('attendance_session', 'student')},
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='date',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='subject',
        ),
    ]
