# Generated by Django 6.0.1 on 2026-02-07 18:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_remove_facedata_created_at_attendance_marked_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='face_image',
            field=models.ImageField(blank=True, null=True, upload_to='student_faces/'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='attendance_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='records', to='backend.attendancesession'),
        ),
    ]
