# Generated by Django 5.2.11 on 2026-02-12 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_student_face_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='face_encoding',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
